# Generated by roxyglobals: do not edit by hand

utils::globalVariables(c(
  "time", # <accuracy>
  "score", # <accuracy>
  "quant_50", # <bias>
  "time", # <bias>
  "score", # <bias>
  "time", # <combine_two_data_frames>
  "raw1", # <combine_two_data_frames>
  "time", # <graph_ensemble>
  "realization", # <graph_ensemble>
  "time", # <graph_observations>
  "score", # <graph_observations>
  "name", # <graph_quantiles>
  "time", # <graph_quantiles>
  "value", # <graph_quantiles>
  "quantile", # <graph_quantiles>
  "conf", # <graph_confidence_intervals>
  "time", # <graph_confidence_intervals>
  "lo", # <graph_confidence_intervals>
  "hi", # <graph_confidence_intervals>
  "time", # <neglog>
  "score", # <neglog>
  "time", # <filter_forecast_time>
  "time", # <join_fcst_obs>
  "time", # <get_time_point>
  NULL
))
